version: "3"
services:
  db:
    image: stnik/yii2-db1-image
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  db2:
    image: stnik/yii2-db2-image
    container_name: db2
    environment:
      - MYSQL_ROOT_PASSWORD=root
  web:
    image: stnik/yii2-image
    container_name: app
    depends_on:
      - db
      - db2
    ports:
      - "80:80"
  redis:
    image: redis:latest
